/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as FeaturesImport } from './routes/features'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardServicePlanServicePlanIdImport } from './routes/dashboard_.servicePlan.$servicePlanId'
import { Route as DashboardReferralUserIdImport } from './routes/dashboard_.referral.$userId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesRoute = FeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardServicePlanServicePlanIdRoute =
  DashboardServicePlanServicePlanIdImport.update({
    id: '/dashboard_/servicePlan/$servicePlanId',
    path: '/dashboard/servicePlan/$servicePlanId',
    getParentRoute: () => rootRoute,
  } as any)

const DashboardReferralUserIdRoute = DashboardReferralUserIdImport.update({
  id: '/dashboard_/referral/$userId',
  path: '/dashboard/referral/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_/referral/$userId': {
      id: '/dashboard_/referral/$userId'
      path: '/dashboard/referral/$userId'
      fullPath: '/dashboard/referral/$userId'
      preLoaderRoute: typeof DashboardReferralUserIdImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_/servicePlan/$servicePlanId': {
      id: '/dashboard_/servicePlan/$servicePlanId'
      path: '/dashboard/servicePlan/$servicePlanId'
      fullPath: '/dashboard/servicePlan/$servicePlanId'
      preLoaderRoute: typeof DashboardServicePlanServicePlanIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/referral/$userId': typeof DashboardReferralUserIdRoute
  '/dashboard/servicePlan/$servicePlanId': typeof DashboardServicePlanServicePlanIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/referral/$userId': typeof DashboardReferralUserIdRoute
  '/dashboard/servicePlan/$servicePlanId': typeof DashboardServicePlanServicePlanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard_/referral/$userId': typeof DashboardReferralUserIdRoute
  '/dashboard_/servicePlan/$servicePlanId': typeof DashboardServicePlanServicePlanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/signup'
    | '/dashboard/referral/$userId'
    | '/dashboard/servicePlan/$servicePlanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/signup'
    | '/dashboard/referral/$userId'
    | '/dashboard/servicePlan/$servicePlanId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/features'
    | '/login'
    | '/signup'
    | '/dashboard_/referral/$userId'
    | '/dashboard_/servicePlan/$servicePlanId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardReferralUserIdRoute: typeof DashboardReferralUserIdRoute
  DashboardServicePlanServicePlanIdRoute: typeof DashboardServicePlanServicePlanIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardReferralUserIdRoute: DashboardReferralUserIdRoute,
  DashboardServicePlanServicePlanIdRoute:
    DashboardServicePlanServicePlanIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/dashboard",
        "/features",
        "/login",
        "/signup",
        "/dashboard_/referral/$userId",
        "/dashboard_/servicePlan/$servicePlanId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/features": {
      "filePath": "features.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/dashboard_/referral/$userId": {
      "filePath": "dashboard_.referral.$userId.tsx"
    },
    "/dashboard_/servicePlan/$servicePlanId": {
      "filePath": "dashboard_.servicePlan.$servicePlanId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
