/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as MyStoryImport } from './routes/my-story'
import { Route as LoginImport } from './routes/login'
import { Route as FeaturesImport } from './routes/features'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as MyStoryServicePlanServicePlanIdImport } from './routes/my-story_.servicePlan.$servicePlanId'
import { Route as MyStoryReferralUserIdImport } from './routes/my-story_.referral.$userId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const MyStoryRoute = MyStoryImport.update({
  id: '/my-story',
  path: '/my-story',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesRoute = FeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MyStoryServicePlanServicePlanIdRoute =
  MyStoryServicePlanServicePlanIdImport.update({
    id: '/my-story_/servicePlan/$servicePlanId',
    path: '/my-story/servicePlan/$servicePlanId',
    getParentRoute: () => rootRoute,
  } as any)

const MyStoryReferralUserIdRoute = MyStoryReferralUserIdImport.update({
  id: '/my-story_/referral/$userId',
  path: '/my-story/referral/$userId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/my-story': {
      id: '/my-story'
      path: '/my-story'
      fullPath: '/my-story'
      preLoaderRoute: typeof MyStoryImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/my-story_/referral/$userId': {
      id: '/my-story_/referral/$userId'
      path: '/my-story/referral/$userId'
      fullPath: '/my-story/referral/$userId'
      preLoaderRoute: typeof MyStoryReferralUserIdImport
      parentRoute: typeof rootRoute
    }
    '/my-story_/servicePlan/$servicePlanId': {
      id: '/my-story_/servicePlan/$servicePlanId'
      path: '/my-story/servicePlan/$servicePlanId'
      fullPath: '/my-story/servicePlan/$servicePlanId'
      preLoaderRoute: typeof MyStoryServicePlanServicePlanIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/my-story': typeof MyStoryRoute
  '/signup': typeof SignupRoute
  '/my-story/referral/$userId': typeof MyStoryReferralUserIdRoute
  '/my-story/servicePlan/$servicePlanId': typeof MyStoryServicePlanServicePlanIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/my-story': typeof MyStoryRoute
  '/signup': typeof SignupRoute
  '/my-story/referral/$userId': typeof MyStoryReferralUserIdRoute
  '/my-story/servicePlan/$servicePlanId': typeof MyStoryServicePlanServicePlanIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/my-story': typeof MyStoryRoute
  '/signup': typeof SignupRoute
  '/my-story_/referral/$userId': typeof MyStoryReferralUserIdRoute
  '/my-story_/servicePlan/$servicePlanId': typeof MyStoryServicePlanServicePlanIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/my-story'
    | '/signup'
    | '/my-story/referral/$userId'
    | '/my-story/servicePlan/$servicePlanId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/my-story'
    | '/signup'
    | '/my-story/referral/$userId'
    | '/my-story/servicePlan/$servicePlanId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/my-story'
    | '/signup'
    | '/my-story_/referral/$userId'
    | '/my-story_/servicePlan/$servicePlanId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MyStoryRoute: typeof MyStoryRoute
  SignupRoute: typeof SignupRoute
  MyStoryReferralUserIdRoute: typeof MyStoryReferralUserIdRoute
  MyStoryServicePlanServicePlanIdRoute: typeof MyStoryServicePlanServicePlanIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MyStoryRoute: MyStoryRoute,
  SignupRoute: SignupRoute,
  MyStoryReferralUserIdRoute: MyStoryReferralUserIdRoute,
  MyStoryServicePlanServicePlanIdRoute: MyStoryServicePlanServicePlanIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/features",
        "/login",
        "/my-story",
        "/signup",
        "/my-story_/referral/$userId",
        "/my-story_/servicePlan/$servicePlanId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/features": {
      "filePath": "features.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/my-story": {
      "filePath": "my-story.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/my-story_/referral/$userId": {
      "filePath": "my-story_.referral.$userId.tsx"
    },
    "/my-story_/servicePlan/$servicePlanId": {
      "filePath": "my-story_.servicePlan.$servicePlanId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
